apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-prod
spec:
  project: default
  source:
    repoURL: 'https://github.com/rajdhavalikar1233/firstapp.git'
    path: src/web/overlays/prod
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: web
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true