apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-prod
spec:
  destination:
    name: ''
    namespace: web
    server: 'https://kubernetes.default.svc'
  source:
    path: src/web/overlays/prod
    repoURL: 'https://github.com/rajdhavalikar1233/firstapp.git'
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-kustomize
  sources: []
  project: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
