kind: Secret
apiVersion: v1
metadata:
  name: mysql-pass
  annotations:
    avp.kubernetes.io/path: "secrets/data/apps/wordpress/sql"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  password: <password>