kind: Secret
apiVersion: v1
metadata:
  name: my-test-app
  annotations:
    avp.kubernetes.io/path: "secrets/data/apps/my-test-app"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  user: <user>
  pass: <pass>
