apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-prod
namePrefix: web
nameSuffix: -v1
resources:
  - ../bases
  - secret.yaml
  - configmap.yaml
  - ingress.yaml
images:
  - name: nginx
    newName: nginx
    newTag: latest