apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80