
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress
  spec:
    ingressClassName: nginx
    rules:
      - host: web.dhavalikars.us
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: web-service-v1
                  port:
                    number: 80
