apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: confluent-for-kubernetes
  repo: https://packages.confluent.io/helm
  version: "0.1033.33"
  releaseName: confluent-operator
  namespace: confluent